/*1. List all unique cities where customers are located. */
Select distinct customer_city from customers;

/*2. Count the number of orders placed in 2017. */
select count(*) from orders
where year(order_purchase_timestamp) = 2017;

/* 3. Find the total sales per category.*/
select p.product_category, sum(py.payment_value) as total_revenue from products as p
join order_items as oi
on oi.product_id = p.product_id
join payments as py
on py.order_id = oi.order_id
group by p.product_category
order by total_revenue desc;

/*4. Calculate the percentage of orders that were paid in installments. */
select round((payments_by_installments /cast(total_payments as float))*100,2) 
as Installment_Percentage from 
(select count(*) as total_payments,
(select count(*) from payments where payment_installments >1) as payments_by_installments
 from payments) a;

/*5. Count the number of customers from each state.*/
select customer_state,count(*) as Total_customers from customers
group by customer_state
order by Total_customers desc;

/*INTERMEDIATE PROBLEMS: 
1. Calculate the number of orders per month in 2018. */
select MONTH(order_purchase_timestamp) as months, count(*) from orders
where year(order_purchase_timestamp) = 2018
group by mONTH(order_purchase_timestamp)
order by MONTH(order_purchase_timestamp) ;

/*2. Find the average number of products per order, grouped by customer city. */
select order_id, avg(total_orders) as avg_orders from (select o.order_id as order_id,count(p.product_category) as total_orders from orders as o
join order_items as oi
on oi.order_id = o.order_id
join products as p
on p.product_id = oi.product_id
join customers as c
on c.customer_id = o.customer_id
group by o.order_id,c.customer_city) a
group by order_id
order by avg_orders desc;


/*3. Calculate the percentage of total revenue contributed by each product category.*/
select category, (total_revenue/total_rev)*100  as pr
from (select distinct p.product_category as category,
sum(py.payment_value) over (partition by p.product_category) as total_revenue,
SUM(PY.payment_value) over () as total_rev
from payments as py
left join order_items as oi
on oi.order_id = py.order_id
join products as p
on p.product_id = oi.product_id) a
order by pr desc;


/*4. Identify the correlation between product price and the number 
of times a product has been purchased.*/
WITH product_summary AS (
    SELECT
        product_id,
        AVG(price) AS price,
        SUM(cast(order_item_id as float)) AS purchase_count
    FROM order_items
    GROUP BY product_id
)
SELECT
(
    COUNT(*) * SUM(price * purchase_count)
    - SUM(price) * SUM(purchase_count)
)
/
SQRT(
    (COUNT(*) * SUM(price * price) - POWER(SUM(price), 2)) *
    (COUNT(*) * SUM(purchase_count * purchase_count) - POWER(SUM(purchase_count), 2))
) AS price_purchase_correlation
FROM product_summary;



/*5. Calculate the total revenue generated by each seller, and rank them by revenue.*/
select s.seller_id,sum(p.payment_value) as revenue, rank() over (order by sum(p.payment_value) desc) as ranks
from sellers as s
join order_items oi
on oi.seller_id = s.seller_id
join payments as p
on p.order_id = oi.order_id
group by s.seller_id
order by revenue desc;

/*1. Calculate the moving average of order values for each customer over their order history. */
with avg_value as (SELECT
   o.customer_id,
    SUM(p.payment_value) / COUNT(o.customer_id) AS avg_order_value
FROM payments as p
join orders as o
on o.order_id = p.order_id
GROUP BY o.customer_id)
SELECT
    o.customer_id,
    o.order_purchase_timestamp,
    av.avg_order_value,
    AVG(av.avg_order_value) OVER (
        PARTITION BY o.customer_id
        ORDER BY o.order_purchase_timestamp
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg_order_value
FROM avg_value av
join orders as o
on av.customer_id = o.customer_id
ORDER BY
    o.customer_id,
    o.order_purchase_timestamp;



/*2. Calculate the cumulative sales per month for each year*/
select MONTH(o.order_purchase_timestamp) as months,year(o.order_purchase_timestamp) as years,
sum(p.payment_value) as rev,
sum(sum(p.payment_value)) over (partition by year(o.order_purchase_timestamp)
order by MONTH(o.order_purchase_timestamp) rows between unbounded preceding and current row) as cum_sales
from payments p
join orders as o
on o.order_id = p.order_id
group by MONTH(o.order_purchase_timestamp),
year(o.order_purchase_timestamp)
order by years,months
;

/*3. Calculate the year-over-year growth rate of total sales.*/
select years, revenue ,round((revenue-previos)/revenue*100,2) as perc_change from
(select year(order_purchase_timestamp) as years , sum(payment_value) as revenue,
lag(sum(payment_value)) over (order by year(order_purchase_timestamp) asc) as previos from orders as o
join payments as p
on p.order_id = o.order_id
group by year(order_purchase_timestamp))a;
/*4. Calculate the retention rate of customers, 
defined as the percentage of customers who make another purchase within
6 months of their first purchase.*/
WITH first_purchase AS (
    SELECT
        oi.order_id,
        MIN(order_purchase_timestamp) AS first_order_date
    FROM order_items oi
    left join orders o 
    on o.order_id = oi.order_id
    GROUP BY oi.order_id
),

repeat_within_6_months AS (
    SELECT DISTINCT
        oi.order_id
    FROM order_items oi
    join orders o
    on o.order_id = oi.order_id
    JOIN first_purchase fp
        ON oi.order_id = fp.order_id
    WHERE o.order_purchase_timestamp > fp.first_order_date
      AND o.order_purchase_timestamp <= DATEADD(MONTH, 6, fp.first_order_date)
)

SELECT
    cast(COUNT(DISTINCT r.order_id) as float) * 100
    / cast(COUNT(DISTINCT f.order_id) as float) AS retention_rate_percentage
FROM first_purchase f
LEFT JOIN repeat_within_6_months r
    ON f.order_id = r.order_id;



/*5. Identify the top 3 customers who spent the most money in each year.*/
WITH yearly_customer_spend AS (
    SELECT
        customer_id,
        YEAR(order_purchase_timestamp) AS order_year,
        SUM(payment_value) AS total_spent
    FROM orders as o
    join payments as p
    on o.order_id = p.order_id
    GROUP BY
        customer_id,
        YEAR(order_purchase_timestamp)
        ),

ranked_customers AS (
    SELECT
        customer_id,
        order_year,
        total_spent,
        DENSE_RANK() OVER (
            PARTITION BY order_year
            ORDER BY total_spent DESC
        ) AS spend_rank
    FROM yearly_customer_spend
)

SELECT
    order_year,
    customer_id,
    total_spent
FROM ranked_customers
WHERE spend_rank <= 3
ORDER BY
    order_year,
    total_spent DESC;

